@url = http://localhost:5127

### Testar a Listagem (Deve vir vazio [] no começo)
GET {{url}}/livros
Accept: application/json

###

### Criar um Livro (POST)
POST {{url}}/livros
Content-Type: application/json

{
  "titulo": "O Senhor dos Anéis",
  "autor": "J.R.R. Tolkien"
}

###

### Criar outro Livro (Para ter mais de um)
POST {{url}}/livros
Content-Type: application/json

{
  "titulo": "1984",
  "autor": "George Orwell"
}

###

### Tentar Deletar o livro com ID 1
DELETE {{url}}/livros/1